import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Card from "../components/Card";
import Button from "../components/Button";
export default function Summary({ room, onBackHome, }) {
    const ordered = room.players.slice().sort((a, b) => b.score - a.score);
    return (_jsx("div", { className: "min-h-[80vh] flex items-center justify-center px-4", children: _jsx("div", { className: "w-full max-w-2xl", children: _jsxs(Card, { className: "!p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-8", children: [_jsx("div", { className: "text-2xl font-medium text-wiki-text", children: "Fin du jeu" }), _jsxs("div", { className: "text-base text-wiki-gray-500", children: ["Partie ", room.code] })] }), _jsxs("div", { className: "space-y-6 mb-8", children: [_jsx("div", { className: "text-xl font-medium text-wiki-text", children: "Classement final" }), ordered.map((p, i) => (_jsxs(Card, { className: "!p-4", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("div", { className: "text-xl font-medium text-wiki-gray-500", children: ["#", i + 1] }), _jsx("div", { className: "text-lg text-wiki-text", children: p.name })] }), _jsxs("div", { className: "text-lg text-wiki-blue", children: [p.score, " pts"] })] }), room.history && (_jsx("div", { className: "space-y-2", children: Object.keys(room.history)
                                            .map((r) => parseInt(r, 10))
                                            .sort((a, b) => a - b)
                                            .map((round) => (_jsxs("div", { className: "bg-wiki-gray-50 rounded p-3", children: [_jsx("div", { className: "flex items-center gap-2 mb-2", children: _jsxs("div", { className: "text-base text-wiki-gray-500", children: ["Manche ", round] }) }), _jsx("div", { className: "text-base text-wiki-text", children: (room.history[round]?.[p.id] || []).map((t, idx) => (_jsxs("span", { children: [idx > 0 && (_jsx("span", { className: "text-wiki-gray-500 mx-2", children: "\u2192" })), decodeURIComponent(t.replace(/_/g, " "))] }, idx))) })] }, round))) }))] }, p.id)))] }), _jsx(Button, { variant: "primary", fullWidth: true, onClick: onBackHome, children: "Retour \u00E0 l'accueil" })] }) }) }));
}
